config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :types, only: [:new, :create]
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/type.rb
class Type < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sing_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end 
end

app/controllers/types_controller.rb
class TypesController < ApplicationController


  def new
    @type = Type.new
  end

  def create
    @type_params = params.require(:type).permit(:name, :description)

    @type = Type.new @type_params
    return redirect_to root_path, notice: "Tipo salvo com sucesso." if @type.save
    flash.now[:alert] = "Não foi possível salvar tipo."
    render 'new'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>TODO APP</h1> 

<%= link_to 'Novo tipo', new_type_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <nav>
      <ul>
        <% if current_user.present? %>
          <li> <%= current_user.email %> </li>
        <% else %>
          <li><%= link_to 'Entrar', new_user_session_path %> | </li>
        <% end %> 
      </ul>
    </nav>
    <%= notice %>
    <%= alert %>
    <%= yield %>
  </body>
</html>

app/views/types/new.html.erb
<h1>Criando um tipo</h1>

<%= form_with(model: @type) do |f| %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.submit 'Salvar' %>
  </div>

<% end %>